### PR TITLE
Convert to rendering via react.js

### PR DESCRIPTION
**Pull request by kizzlebot**
Not sure if this will be accepted.  Recreated current site to use React.js.  Bundling handled via `webpack` (run `npm run build` to generate `/dist/bundle.js` file) and development mode features `hot-module-replacement` (run `npm start`) for live-updates to react components.

### CODE REVIEW

**Comment by ryanvgates** [comment]
I would definitely be interested in experimenting with it as our html site is kind of plain right now. I would want @RobDavis and @qtrandev to give there input as well.

I tried to build from your repository and I got the following error.

> ryan@ryan-CM5570 ~/Documents/github/kizzlebot/CodeForftL.github.io $ npm run build
\> codeforftl@1.0.0 build /home/ryan/Documents/github/kizzlebot/CodeForftL.github.io
\> webpack
sh: 1: webpack: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
npm ERR! not ok code 0
ryan@ryan-CM5570 ~/Documents/github/kizzlebot/CodeForftL.github.io $ 

Is there something else that I need to do to test it out?

**Comment by ryanvgates** [comment]
@kizzlebot Thank you for the instructions. I just tried them and got further but still got a different error.

> ryan@ryan-ThinkPad-T430:~/Documents/kizzlebot/CodeForftL.github.io$` npm run build
> 
> > codeforftl@1.0.0 build /home/ryan/Documents/kizzlebot/CodeForftL.github.io
> > webpack
> 
> sh: 1: webpack: not found
> 
> npm ERR! Linux 4.2.0-27-generic
> npm ERR! argv "/home/ryan/.nvm/versions/node/v5.9.1/bin/node" "/home/ryan/.nvm/versions/node/v5.9.1/bin/npm" "run" "build"
> npm ERR! node v5.9.1
> npm ERR! npm  v3.7.3
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! codeforftl@1.0.0 build: `webpack`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the codeforftl@1.0.0 build script 'webpack'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the codeforftl package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     webpack
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs codeforftl
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls codeforftl
> npm ERR! There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ryan/Documents/kizzlebot/CodeForftL.github.io/npm-debug.log

reactjs-version-webpacknotfounderror

**Comment by ryanvgates** [comment]
When I opened up https://codeforftl-kizzlebot.c9users.io/index.html and hit F12, I noticed that there were several warnings like the one below.

> SyntaxError: unreachable expression after semicolon-less return statement

What are those from? How would hosting work for reactjs code on github?

**Comment by daarons** [comment]
I have no experience with node or react (learning them now), but when I first downloaded the zip file I opened the index.html file and saw some errors: the 3 "view details" buttons under the main pic don't link to anything. I tried putting links around them myself but it didn't work. Also, there's a space missing in the contact session. I tried inserting a space and &nbsp; but I couldn't get it to work. 

Now, I'm trying to build the project, but keep getting this error:

```
C:\Users\David\Desktop\CodeForftL.github.io-master\dist>npm run build

> codeforftl@1.0.0 build C:\Users\David\Desktop\CodeForftL.github.io-master
> webpack --config webpack.config.js

Hash: ce83eeb6eac90e89e5cd
Version: webpack 1.13.0
Time: 18464ms
    Asset    Size  Chunks             Chunk Names
bundle.js  747 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 159 hidden modules

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'bootstrap-webpack' in C:\Users\D
avid\Desktop\CodeForftL.github.io-master\src
 @ ./src/index.js 5:0-56

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react-dom' in C:\Users\David\Des
ktop\CodeForftL.github.io-master\src
 @ ./src/index.js 9:15-35

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'style' in C:\Users\David\Desktop
\CodeForftL.github.io-master\src
 @ ./src/index.js 6:0-29

ERROR in ./src/App.js
Module not found: Error: Cannot resolve module 'react-dom' in C:\Users\David\Des
ktop\CodeForftL.github.io-master\src
 @ ./src/App.js 6:15-35
```

And now, when I open the index.html it doesn't load the page.

**Comment by daarons** [comment]
Got the modules installed now. I got a small error but it doesn't look like it's a big deal so I ignored it:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.11
```

Then I ran npm start and it said that it was listening at localhost:3000. I opened it up in my browser and there was only a blank page. The title of the page was displayed on the tab and the icon was too. I looked at the source code for the page and it was the index.html source code, but for whatever reason it wasn't displaying anything.

**Comment by daarons** [comment]
I tried. I get the same error. It's not compatible with my operating system or architecture :(

**Comment by daarons** [comment]
@kizzlebot I was probably doing something dumb. I just finished a Git course yesterday actually, but before I was downloading the zip files and not cloning. Is there a difference between cloning and downloading? Regardless, everything went much faster now and all the dependencies installed with less errors, though that architecture warning didn't go away.

Anyway, yes, I managed to get the react-webpack-babel working. Then I tried a clean install of the website, checked the console log and saw that jQuery was missing. I stuck in jQuery using a CDN link and it loaded perfectly! I fixed the small errors with the button links and the missing whitespace. 

So now I have that in my repo. I'm going to give you a pull request (that's what I should do, right?) so that you can look it over. I put the changes in 3 commits. 
- One for adding the jQuery link
- One for fixing the buttons and whitespace
- And one that I'm honestly not sure what it changed exactly. It changed a lot in the bundle.js.

**Comment by daarons** [comment]
@ryanvgates Everything works for me! I think it's ready to be committed.

**Comment by ryanvgates** [comment]
Will I need to do anything to update it besides merge in the pull request? Is there a url that I can view your repository https://github.com/kizzlebot/CodeForftL.github.io?

**Pull request closed without merging**
